mongo_homepage:
    path:     /
    defaults: { _controller: MongoBundle:Queries:results }

mongo_crear:
    path: /crear
    defaults: {_controller: MongoBundle:Default:crear}

mongo_eliminar:
    path: /eliminar/{id}
    defaults: {_controller: MongoBundle:Default:eliminar, id: null}

mongo_buscar_todos:
    path: /ver_autores
    defaults: {_controller: MongoBundle:Default:verAutores}

mongo_buscar_nombre:
    path: /buscar_nombre
    defaults: {_controller: MongoBundle:Default:buscarNombre}
    
listar_nodos:
    path:     /listarNodos
    defaults: { _controller: MongoBundle:Crawler:listarNodos }

index:
    path:     /index
    defaults: { _controller: MongoBundle:Usuario:index }

mongo_prueba:
    path: /prueba
    defaults: {_controller: MongoBundle:Queries:prueba}

mongo_authors_article:
    path: /importantAuthors
    defaults: { _controller: MongoBundle:Queries:importantAuthors}

mongo_sexenios:
    path: /sexenios
    defaults: {_controller: MongoBundle:Queries:sexenios }

    
mongo_table_authors:
    path: /tableAuthors
    defaults: {_controller: MongoBundle:Queries:tableAuthors }
    
    
mongo_table_important_authors:
    path: /tableImportantAuthors
    defaults: {_controller: MongoBundle:Queries:tableImportantAuthors }
    
mongo_table_sexenios_authors:
    path: /tableSexeniosAuthors
    defaults: {_controller: MongoBundle:Queries:tableSexeniosAuthors } 
    
mongo_table_inadecuate_authors:
    path: /tableInadecuateAuthors
    defaults: {_controller: MongoBundle:Queries:tableInadecuateAuthors } 
    
mongo_table_unproductive_authors:
    path: /tableUnproductiveAuthors
    defaults: {_controller: MongoBundle:Queries:tableUnproductiveAuthors }    
  
mongo_table_traveller_authors:
    path: /tableTravellerAuthors
    defaults: {_controller: MongoBundle:Queries:tableTravellerAuthors } 
    
mongo_table_editor_authors:
    path: /tableEditorAuthors
    defaults: {_controller: MongoBundle:Queries:tableEditorAuthors }  
    
mongo_table_sociable_authors:
    path: /tableSociableAuthors
    defaults: {_controller: MongoBundle:Queries:tableSociableAuthors }
    
mongo_table_stable_authors:
    path: /tableStableAuthors
    defaults: {_controller: MongoBundle:Queries:tableStableAuthors }     